### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by elkhrt** [jhtschultz/roshambo#1]
There's an out-of-bounds access in Greenberg. This change fixes it, but I don't know if its correct:

\<		ROSHAMBO_BOT_gear[i][ROSHAMBO_BOT_T] = ROSHAMBO_BOT_gear[i][ROSHAMBO_BOT_T] % 9;
\>		ROSHAMBO_BOT_gear[i][ROSHAMBO_BOT_T] = ROSHAMBO_BOT_gear[i][ROSHAMBO_BOT_T] % 3;

**Comment by jhtschultz** [comment]
I'll take a closer look at Greenberg's code and add the fix unless there's a clear reason not to. Never ran into any issues with Greenberg before, is there anything in particular that triggered this error? 

And thanks for catching this!

**Comment by elkhrt** [comment]
Thanks! It was just picked up by automated testing.

**Comment by jhtschultz** [comment]
Fixed! With the modification, Greenberg still won every tournament I ran. Greenberg's code is pretty opaque, so if this resolves the memory error without negatively impacting performance, that's correct enough for me. Thanks again!
